### ISSUE TITLE
Registered '*' command doesn't fire ever

### ISSUE THREAD

**Issue by technicalpickles** [kucoe/cline#5]
I was trying out as a possible replacement for readline in [hubot's shell adapter](http://github.com/github/hubot), and found that the '*' command doesn't seem to ever fire.

I added some debug output to the end of `parse` like:

```javascript
    console.log('should I use *?');
    console.log('resp is ' + utils.inspect(resp));
    console.log('commands is ' + utils.inspect(this.commands));
    if (!resp && this.commands['*']) {
        console.log('about to *')
        resp = this.commands['*'].listener(str);
    }
```

When I parse some output, I got this output:

```
should I use *?
resp is null
commands is { map: [Function],
  '\\*': { cmd: '*', desc: '', args: {}, listener: [Function] },
  history: { cmd: 'history', desc: '', args: {}, listener: [Function] } }
```

It seems that `command` is escaping the * command name. Either '*' by itself needs to be not escaped when added to `this.commands` (https://github.com/kucoe/cline/blob/master/index.js#L272), or it needs to be escaped when checking it in `parse` (https://github.com/kucoe/cline/blob/master/index.js#L317)

I tested the former by patching my node_modules/cline, and that seemed to do the trick.

**Comment by technicalpickles** [comment]
A workaround I found was to manipulate the `cli.commands` after registering, like:

```javascript
https://github.com/kucoe/cline/issues/5
cli.commands['*'] = cli.commands['\\*']
```

**Comment by becevka** [comment]
Hi, thanks for contribution.
Eventually, you could workaround with registering command like this
```js
cli.command('{anything}', 'parses any input', {anything: '.*'}, function (input) {
    console.log(input);
});
```
But obviously that is a bug as I forgot about special wildcard pattern when escaping commands body.

**Comment by technicalpickles** [comment]
Confirmed this works in 0.8.2 :+1:
